# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='./upload')),
                ('ctime', models.DateTimeField()),
            ],
            options={
                'db_table': 't_upload_file',
            },
        ),
        migrations.CreateModel(
            name='ValuePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='营业分部代码')),
                ('category', models.CharField(max_length=32, verbose_name='车类别')),
                ('vehicle', models.CharField(max_length=32, verbose_name='具体车型')),
                ('effective_date', models.DateField(default='2017-11-12', verbose_name='价格代码生效日期')),
                ('effective_first', models.DateField(verbose_name='价格代码有效第一日')),
                ('effective_last', models.DateField(verbose_name='价格代码有效最后一日')),
                ('value', models.CharField(max_length=32, verbose_name='价格代码')),
                ('src', models.CharField(max_length=32, verbose_name='预订方式')),
            ],
            options={
                'db_table': 't_value_plan',
            },
        ),
    ]
